# Generated by Django 3.2.10 on 2022-09-11 08:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referensi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_dibuat', models.DateTimeField(auto_created=True)),
                ('dibuat_oleh', models.CharField(max_length=50)),
                ('diperbaharui_oleh', models.CharField(max_length=50)),
                ('waktu_diperbaharui', models.DateTimeField(auto_now=True)),
                ('tensi', models.CharField(max_length=100)),
                ('HB', models.CharField(max_length=100)),
                ('LEUCO', models.CharField(max_length=100)),
                ('BT', models.CharField(max_length=100)),
                ('GDS', models.CharField(max_length=100)),
                ('ERY', models.CharField(max_length=100)),
                ('CT', models.CharField(max_length=100)),
                ('golongan_darah', models.CharField(max_length=100)),
                ('HBSAG', models.CharField(max_length=100)),
                ('HT', models.CharField(max_length=100)),
                ('THROMBO', models.CharField(max_length=100)),
                ('HIV', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_dibuat', models.DateTimeField(auto_created=True)),
                ('dibuat_oleh', models.CharField(max_length=50)),
                ('diperbaharui_oleh', models.CharField(max_length=50)),
                ('waktu_diperbaharui', models.DateTimeField(auto_now=True)),
                ('nomor_seri', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('nomor_identitas', models.CharField(max_length=16, unique=True)),
                ('tipe_identitas', models.CharField(max_length=29)),
                ('tempat_lahir', models.CharField(max_length=30)),
                ('tanggal_lahir', models.DateField(max_length=30)),
                ('umur', models.CharField(max_length=50)),
                ('jenis_kelamin', models.CharField(max_length=1)),
                ('alamat', models.CharField(max_length=100)),
                ('daerah', models.CharField(max_length=50)),
                ('pulau', models.CharField(max_length=50)),
                ('nomor_telepon', models.CharField(max_length=15)),
                ('nama_keluarga', models.CharField(max_length=50)),
                ('nomor_telepon_keluarga', models.CharField(max_length=15)),
                ('perlu_rescreen', models.BooleanField(default=False)),
                ('perlu_radiologi', models.BooleanField(default=False)),
                ('perlu_ekg', models.BooleanField(default=False)),
                ('diagnosa', models.CharField(max_length=50, null=True)),
                ('nomor_antrian', models.CharField(max_length=10, null=True)),
                ('tanggal_nomor_antrian', models.DateTimeField(null=True)),
                ('last_status', models.CharField(max_length=30, null=True)),
                ('komentar', models.CharField(max_length=255, null=True)),
                ('penyakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referensi.penyakit')),
                ('puskesmas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referensi.puskesmas')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningPasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_dibuat', models.DateTimeField(auto_created=True)),
                ('dibuat_oleh', models.CharField(max_length=50)),
                ('diperbaharui_oleh', models.CharField(max_length=50)),
                ('waktu_diperbaharui', models.DateTimeField(auto_now=True)),
                ('telah_lewat_cek_tensi', models.BooleanField(null=True)),
                ('jam_cek_tensi', models.DateTimeField(null=True)),
                ('telah_lewat_pemeriksaan', models.BooleanField(null=True)),
                ('petugas_cek_tensi', models.CharField(max_length=50, null=True)),
                ('jam_pemeriksaan', models.DateTimeField(null=True)),
                ('petugas_pemeriksaaan', models.CharField(max_length=50, null=True)),
                ('telah_lewat_cek_lab', models.BooleanField(null=True)),
                ('jam_cek_lab', models.DateTimeField(null=True)),
                ('petugas_cek_lab', models.CharField(max_length=50, null=True)),
                ('telah_lewat_cek_radiologi', models.BooleanField(null=True)),
                ('jam_cek_radiologi', models.DateTimeField(null=True)),
                ('petugas_cek_radiologi', models.CharField(max_length=50, null=True)),
                ('tipe_hasil_rontgen', models.CharField(max_length=5, null=True)),
                ('nomor_kertas_penyerahan', models.CharField(max_length=50, null=True)),
                ('telah_lewat_cek_ekg', models.BooleanField(null=True)),
                ('jam_cek_ekg', models.DateTimeField(null=True)),
                ('petugas_cek_ekg', models.CharField(max_length=50, null=True)),
                ('telah_lewat_cek_kartu_kuning', models.BooleanField(null=True)),
                ('jam_cek_kartu_kuning', models.DateTimeField(null=True)),
                ('petugas_cek_kartu_kuning', models.CharField(max_length=50, null=True)),
                ('nomor_kartu_kuning', models.CharField(max_length=20)),
                ('pasien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pasien.pasien')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KartuKuning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_dibuat', models.DateTimeField(auto_created=True)),
                ('dibuat_oleh', models.CharField(max_length=50)),
                ('diperbaharui_oleh', models.CharField(max_length=50)),
                ('waktu_diperbaharui', models.DateTimeField(auto_now=True)),
                ('nomor', models.CharField(max_length=10)),
                ('tanggal_operasi', models.DateField(null=True)),
                ('jam_operasi', models.TimeField(null=True)),
                ('perhatian', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
                ('status', models.CharField(max_length=10)),
                ('komentar', models.CharField(max_length=255, null=True)),
                ('pasien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pasien.pasien')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='pasien',
            constraint=models.UniqueConstraint(fields=('nama', 'tanggal_lahir'), name='unique_name_and_dob'),
        ),
    ]
