# Generated by Django 3.2.10 on 2022-09-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpasien',
            name='waktu_dibuat',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='kartukuning',
            name='nomor',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='kartukuning',
            name='waktu_dibuat',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='waktu_dibuat',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='screeningpasien',
            name='waktu_dibuat',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
