# Generated by Django 3.2.10 on 2022-09-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0002_auto_20220913_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasien',
            name='nomor_antrian_pertama',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pasien',
            name='tanggal_nomor_antrian_pertama',
            field=models.DateTimeField(null=True),
        ),
    ]
