# Generated by Django 3.2.10 on 2022-09-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0004_auto_20220916_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='nomor_telepon',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='nomor_telepon_keluarga',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='nomor_telepon_pendamping',
            field=models.CharField(max_length=30),
        ),
    ]
