# Generated by Django 3.2.10 on 2022-09-18 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0005_auto_20220918_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpasien',
            name='pasien',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='pasien.pasien'),
            preserve_default=False,
        ),
    ]
