# Generated by Django 3.2.10 on 2022-09-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0006_detailpasien_pasien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpasien',
            name='BT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detailpasien',
            name='CT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detailpasien',
            name='ERY',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detailpasien',
            name='GDS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detailpasien',
            name='HB',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detailpasien',
            name='HBSAG',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detailpasien',
            name='HIV',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detailpasien',
            name='HT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detailpasien',
            name='LEUCO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detailpasien',
            name='THROMBO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detailpasien',
            name='golongan_darah',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detailpasien',
            name='tensi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
