# Generated by Django 3.2.10 on 2022-09-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0008_alter_pasien_nomor_identitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kartukuning',
            name='komentar',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
