# Generated by Django 4.1.1 on 2022-09-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Penyakit",
            fields=[
                (
                    "nama",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Puskemas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puskesmas", models.CharField(max_length=30)),
                ("pulau", models.CharField(max_length=30)),
            ],
        ),
    ]
