# Generated by Django 3.2.10 on 2022-09-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penyakit',
            fields=[
                ('nama', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Puskesmas',
            fields=[
                ('puskesmas', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pulau', models.CharField(max_length=30)),
            ],
        ),
    ]
